version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - ./static:/app/static
      - ./server/instance:/app/server/instance
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=project_management
      - DATABASE_URL=postgresql+psycopg2://admin:admin123@db/project_management
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=project_management
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:delegated
    networks:
      - app-network
    command: postgres -c 'max_connections=200'

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: {}